### ISSUE TITLE
Trouble shooting : Frontend index.html이 제대로 배포되지 않는 문제를 확인

### ISSUE THREAD

**Issue by youngkwangjoo** [glory-coffee-project/back-end-coffee#43]
## 상황

프론트엔드에서  login page button이 안눌리는 현상을 확인하다가 front index.html이 최신 업데이트되어 배포되지 않고 있음을 확인함

## 해결방법

우선 front docker container는 2개로 관리를 하고 있었음

frontend_container는 인증 및 배포, 하나는 front_nginx르에 배포, 빌드 등을 관리하고 있었음

과거 업데이트 index 파일은 nginx에서 배포중임

문제 원인을 찾기 위해 .dist 파일을 찾아본 결과 nginx container에서 배포중인걸 확인

배포와 빌드가 나뉘어서 문제가 발생하는 것인가 생각이 들어 우선 컨테이너를 합치기로했음

```
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile 
    container_name: frontend-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot:/var/www/certbot
```
로 compose file을 수정하고 컨테이너를 통합한 뒤에 배포를 진행함
